### PR TITLE
Separating replay saving and its dialog into two distinct functions

### PR DESCRIPTION
**Pull request by SergioMartin86**
Separating replay saving and its dialog into two distinct functions

This is so that I can call the saving function without having the dialog shown. No other changes made.

### CODE REVIEW

**Comment by NagyD** [comment]
I see you (accidentally?) changed the indentation of the involved functions.
I'd prefer if you changed it back so that the "Files changed" tab showed only what you actually changed.
Thank you in advance.

**Comment by SergioMartin86** [comment]
Hi David,

I believe I solved it now :) Thank you

(have you considered using clang-format or similar tool to automatize styling?, here's an example from one of my repos https://github.com/cselab/korali/blob/master/.clang-format)

**Comment by NagyD** [comment]
It's better now, but the part in the new `save_recorded_replay` function still has a different indentation from the original.
Please look at the "Files changed" tab.

Also, did you add the overflow fix to this pull request by mistake?

**Comment by SergioMartin86** [comment]
Yes, I mixed things up by accident. Let me fix this up.

**Pull request closed without merging**
