### PR TITLE
Replays under Windows

### PR DESCRIPTION
**Pull request by segrax**
Have added the necessary code to list directories on Windows, and added empty stubs if the 'USE_REPLAY' definition isn't set

### CODE REVIEW

**Comment by Falcury** [comment]
I am not sure if I understand what the problem is (replays listing works fine on Windows, at least if you compile using MinGW) 

I suppose you mean that the code in list_replay_files() is not compatible with Visual Studio?

Then, can't we merge the implementations of list_replay_files() using the preprocessor to abstract away the API differences? 
That way, we don't have a duplicate of the same procedure (which is a headache if something needs changing later on).

Also, why do there need to be stubs if USE_REPLAY is not defined? I don't think this is necessary?

**Comment by segrax** [comment]
Yeah, didn't have MingW installed and was building from VS.

We probably could merge them, i just wiped that up to get it building and figured it might be helpful

I added the stubs because it appeared the define must of been their for a reason, if not.. i guess its better to just remove the ifdef than add that mess of empty functions (I disabled the define originally to get it building under VS, without having to add the Windows file API uses)

**Comment by NagyD** [comment]
I tried to compile without `USE_REPLAY` defined. I got only one compile error.
I fixed that here: 2e87ff14cfba0f209d3cbd008a0a7ec03e8b7530

**Comment by Falcury** [comment]
Compiling with Visual Studio should now work better.
I also created a script (src/build.bat) for compiling SDLPoP under Windows, as an alternative to NMake. Hopefully that will be helpful as well!

**Pull request closed without merging**
