### PR TITLE
Fix one corrupted sword attack audio sample

### PR DESCRIPTION
**Pull request by zaps166**
DIGISND1.DAT: At position 0x693B replace 0xA1 by 0x80 which is silence.
This prevents "click" at the end of sword attack sound.

### CODE REVIEW

**Comment by Falcury** [comment]
Hm, somehow I never noticed before that there was a click after the swooshing sound!

**Comment by zaps166** [comment]
First sound is before the fix, second is after the fix.

sound

[Sound.wav](https://github.com/NagyD/SDLPoP/files/664429/Sound.txt) - replace `.txt` by `.wav`

**Comment by NagyD** [comment]
Indeed... You must have good ears! :ear: :)

**Comment by zaps166** [comment]
> You must have good ears!

:)

Btw. I think that something is wrong with resampling quality (from 11025 Hz) - I'll look at this later :)

**Pull request merged**
