### PR TITLE
Fix warnings on non-explicit casts and use of comma as a binary operator

### PR DESCRIPTION
**Pull request by berikv**
This time double checked to work and not break the dialogs.
I did notice that, in the copy protection level, the letters are missing above the bottles. Is that a pre-existing issue?

Is the name / location of setup_dialog_settings acceptable?

### CODE REVIEW

**Comment by NagyD** [comment]
> I did notice that, in the copy protection level, the letters are missing above the bottles. Is that a pre-existing issue?

I have checked it now, it has existed since v1.21.
It was introduced by commit e836a4784cd7430936ab19e4be79b2f394298610.

Apparently nobody played the potions level since then.


> Is the name / location of setup_dialog_settings acceptable?

It is, but you should add a comment explaining why this roundabout initialization is needed.

I figured out why the first two members of the `dialog_settings_type` struct are not aligned according to their types.
There are some improperly nested `#pragma pack` directives around this struct, which cause it to be byte-packed (no alignment, no padding).
Byte-packing is needed only for types which are read from or written to files.

I now fixed the pragmas in 40e7808c619195eb6ed043a0058dae7c7d554075.
Can you check if it fixes the "pointer not aligned" errors?

**Comment by berikv** [comment]
Tested 40e7808 and compiles on M1! 🎉

I'll remove the dialog_settings code and do a new pull request with the other changes, if you feel they're helpful.

**Comment by NagyD** [comment]
> Tested 40e7808 and compiles on M1! 🎉

That's good to hear!

> I'll remove the dialog_settings code and do a new pull request with the other changes, if you feel they're helpful.

Yes, thank you.

In 283092ac36899a9f66cb0560ccfee062bb25c6bc, I think `var_6` should be assigned only once, before the loop.

**Comment by berikv** [comment]
> > I'll remove the dialog_settings code and do a new pull request with the other changes, if you feel they're helpful.
> 
> Yes, thank you.
> 
> In [283092a](https://github.com/NagyD/SDLPoP/commit/283092ac36899a9f66cb0560ccfee062bb25c6bc), I think `var_6` should be assigned only once, before the loop.

Adjusted the var_6 assignment and removed the dialog_settings related code from this pull request.

**Comment by NagyD** [comment]
> I did notice that, in the copy protection level, the letters are missing above the bottles. Is that a pre-existing issue?

This was finally fixed in #299.

**Pull request merged**
