### PR TITLE
[WIP] Scripting feature (using libtcc)

### PR DESCRIPTION
**Pull request by Falcury**
This adds scripting capabilities through the use of [libtcc](http://bellard.org/tcc/) (part of TinyCC, a.k.a. tiny C compiler).

The basic idea is that a C script containing modifications is compiled at runtime, after which it is linked with the host process in memory (SDLPoP). SDLPoP and the compiled script can then access each other's functions and variables as necessary.

The capabilities are still quite limited. But it will be easy to expand the feature as we want in the future.

**New files added**:
* `data/script/lib/libtcc1.a` - part of libtcc; it is needed so that functions like `printf` can work in scripts
* `data/script/pop_script.h` - header file, to be #included in the scripts. It contains declarations for use in scripts

*Edit (February 2): updated the list of the available functions.*
*Edit (February 9): updated the list again. The scripting feature should be ready for testing now.*
*Edit (March 20): removed the list of available functions in the description (but you can easily find the functions in `pop_script.h`). I added some brief documentation explaining how you can write scripts in `Readme.txt`.*
*Edit (May 21): separated out the mod organisation changes in #69)*

### CODE REVIEW

**Comment by Falcury** [comment]
Thanks. 

What do you mean exactly with the room linking and door linking APIs?

So as I understand it `tile_packed_type` allows manipulating the tiletype and modifier together? That sounds like a really good solution for the editor (because fg/bg combinations often represent separate placeable objects, right?). 
I'm not sure about the scripts though, because when manipulating gameplay things, you're often checking and changing the tiletype and modifier separately. So there is less of an advantage.

Iterating over all rooms using `tile_global_location_type` is a bit less code to write, but apart from that it's not a great advantage over a double `for` loop, I think? 
I do agree that it is nice to have a single 'global' coordinate of sorts.

I'll think about it. From the mod writer's point of view, perhaps the types are too cryptic to use comfortably in the scripts themselves. I think it will be very important to keep the abstractions that we'll expose to end users as simple and intuitive as possible. I should really look into it more, I haven't looked at your code thoroughly enough!

**Comment by ecalot** [comment]
I agree, scripting should be easier than editing the game directly in C. Anyways, the idea of the macros could be helpful in some cases, just think about it. Room linking api is useful to iterate over all the rooms skipping the rooms outside the game; another feature is to move through an X-Y coordinate system. Door linking api is useful to add/remove button-door triggers on the fly.

**Comment by Falcury** [comment]
Some recent additions:
* Added some documentation to Readme.txt.
* Mods can be played from their own individual folders in `mods/`, and a new `levelset` option in SDLPoP.ini to choose which mod to load.
* Script variables can get stored in savestates, and restored from them.

The scripting feature is far from finished. But the basic functionality is far enough so that it can be tested now. @NagyD, feel free to add this into a separate branch, if you want! 

It will be good to get some criticism, if there are things that should be done differently.

Note that here is a dependency on libtcc. However, I have not edited the Makefile so that it will link properly (I don't know how this should be done).

**Comment by Falcury** [comment]
I am closing this pull request for now, because this feature probably isn't good enough yet and I am not making much progress (may reopen in the future).

**Pull request closed without merging**
