### PR TITLE
Fix graphics bug with SDL 2.0.5

### PR DESCRIPTION
**Pull request by zaps166**
Fix a bug that some things are not cleared on screen, e.g. enemy lives or potion animated "dots".

I hope this doesn't break anything else, please test :)

*Maybe is it better remove the dead code?*

### CODE REVIEW

**Comment by Falcury** [comment]
I can confirm that the fix works for me as well.
There may be other places that still need fixing (in a similar way perhaps?)
It also seems to happen for gates that open (just the top part of the gate animation).

**Comment by NagyD** [comment]
The fix works for me. Not just with SDL 2.0.5 but also with 2.0.4 and 2.0.3.

Previous bubbles, guard HPs, and gate tops are removed by drawing an image with a mono-black blitter. (`blitters_40h_mono` or `blitters_9_black`)

So `SDL_SetColorKey` changes opaque black to transparent?

**Comment by zaps166** [comment]
> So `SDL_SetColorKey` changes opaque black to transparent?

Hmm, maybe yes... According to [docs](https://wiki.libsdl.org/SDL_SetColorKey) and [tutorial](http://www.lazyfoo.net/SDL_tutorials/lesson05/index.php) it sets the chosen color (`0` in this case (black)) to transparent. I've never used this function before :)

**Comment by NagyD** [comment]
I know what is it for, but I thought that with `SDL_PIXELFORMAT_ARGB8888`, color 0 would change *transparent* black (Alpha=0) to transparent.
Anyway, this colorkey thing is redundant exactly because the transparent color is already transparent. :smile:

**Pull request merged**
