### PR TITLE
Level Editor

### PR DESCRIPTION
**Pull request by ecalot**
There is still too much to do, but the basics are done and is fully functional.

### CODE REVIEW

**Comment by NagyD** [comment]
I would like to merge this into a new branch (instead of master) if possible.

**Comment by ecalot** [comment]
That'd be great. A lot has changed and a lot of testing is needed. I've added the USE_EDITOR macro to keep tracking all modifications to the source outside editor.c in case you wanted to merge in master, but as there are so many commits, I can maintain a separated editor branch.

**Comment by NagyD** [comment]
> I would like to merge this into a new branch (instead of master) if possible.

Done: https://github.com/NagyD/SDLPoP/tree/editor

**Comment by ecalot** [comment]
No problem.

**Comment by ecalot** [comment]
I'm closing this PR as noted in [a comment in Issue #31](https://github.com/NagyD/SDLPoP/issues/31#issuecomment-247266582), there is no need to merge.

**Pull request closed without merging**
