### PR TITLE
Fix compiler warning on intentional fallthrough

### PR DESCRIPTION
**Pull request by bonki**

### CODE REVIEW

**Review by mooskagh — COMMENTED** [review]
FYI starting from C23, there will be C attributes, see https://en.cppreference.com/w/c/language/attributes

So it may make sense to write something like:
```c
#ifdef __has_c_attribute(fallthrough)
[[fallthrough]]
#endif
```

**Comment by bonki** [comment]
Indeed, and `gcc` already has a non-standard attribute for this as well (not sure if this is true for `clang` in C-mode). 
I just picked what's already in use as a marker to be consistent with the rest of the current code base.

**Comment by NagyD** [comment]
I have merged this for now.

@mooskagh, I tried your code.

In Dev-C++ I need one more check:
```c
#ifdef __has_c_attribute
#if __has_c_attribute(fallthrough)
[[fallthrough]];
#endif
#endif
```

Instead of checking this every time, I think it would be better to define a macro which expands to `[[fallthrough]]` if it's supported, or to nothing otherwise.

**Comment by NagyD** [comment]
> Instead of checking this every time, I think it would be better to define a macro which expands to `[[fallthrough]]` if it's supported, or to nothing otherwise.

Here is it on a new branch: 96dfb3d2e3970b7495efd81ba7fde1ad8a16149d

**Pull request merged**
