### PR TITLE
Fix Linux Mint 18 compilation problem

### PR DESCRIPTION
**Pull request by JuanMiguelBG**
Fix Linux Mint 18 compilation problem:
`
gcc  main.o data.o seg000.o seg001.o seg002.o seg003.o seg004.o seg005.o seg006.o seg007.o seg008.o seg009.o seqtbl.o replay.o options.o -o ../prince -lSDL2_image -lSDL2_mixer -lSDL2
/usr/bin/ld: seg000.o: referencia sin definir al símbolo 'atan2@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:28: fallo en las instrucciones para el objetivo '../prince'
make: *** [../prince] Error 1`

Add -lm parameter to compilate on Makefile.

### CODE REVIEW

**Comment by NagyD** [comment]
Thanks for the fix, but...

Why does your first commit contain my last commit? And what's with those two "restore" commits? :confused:

**Comment by JuanMiguelBG** [comment]
In the first commit, there are files modified by codification problem.

The two latest commit, I only want to restore your original files.

You can discard this pull request and yuo can add the fix.

**Comment by Falcury** [comment]
I found this, explaining why the math functions are not implemented in `libc.a` / `libc.so`:
http://stackoverflow.com/questions/1033898/why-do-you-have-to-link-the-math-library-in-c

But it's still puzzling to me as to why something as simple as a trigonometry function requires special link instructions...
Apparently, it's not a problem on Windows.

If we fix this issue by linking against libm, then the (non-Windows) CMake configuration in `CMakeLists.txt` should be updated as well.

Or, to circumvent the problem, we could use something else instead of libm's `atan2()`.
I found some alternatives here:
http://stackoverflow.com/questions/11930594/calculate-atan2-without-std-functions-or-c99

**Comment by NagyD** [comment]
Added libm to Makefile and CMakeLists : d15e57bfd1d2ff309a63c691662cb53f347af5b8
I hope I edited the CMakeLists correctly. If not, then please fix it!

`libm` also exists under Windows, by the way, it just does not contain any functions.
It's just a dummy.

**Pull request closed without merging**
