### PR TITLE
Update to v1.23

### PR DESCRIPTION
**Pull request by javierdlr**
updated amigaos4 SDLPoP with latest main v1.23 changes.

### CODE REVIEW

**Comment by javierdlr** [comment]
Ooops forget it just found I did pull to wrong branch :-(

**Comment by NagyD** [comment]
This gave me loads of merge conflicts.
I went through them all by hand to ensure all merges are done right, and still I got some compiler errors *after* I committed the merge.

In the long term it would be better if I could merge `amigaos4` into `master`, and the same source could be compiled for all systems.

**Comment by NagyD** [comment]
Okay, I have merged `amigaos4` into `master`.
I have verified that it compiles and runs correctly on Windows.
Could you verify the same on AmigaOS?

**Comment by javierdlr** [comment]
1st sorry for answering so late.
2nd sorry for all the hassle while merging amigaos4<->master

Downloaded and build/mAKE amigaos4 works, but I have to add some defines in makefile.amigaos4, will send it ASAP.

**Pull request merged**
